:hp-tags: Tomcat JSP Maven

= How to compile JSP with Tomcat and Maven faster

When I must pre-compile JSP with tomcat, it's usually pain because it takes a lot of time.
Let's see How compile this faster.

== How to compile JSP

If I must compile for tomcat, I usually take this Maven plugin : https://github.com/leonardehrenfried/jspc-maven-plugin
I take this plugin because I think it's pretty simple, and it give availabilty to add includes/excludes of jsp.
This Maven config to the job in War project : 

[source,xml]
====
<web-app *metadata-complete="true"*>

TODO

</web-app>
====

== Some problems of this plugin

If we have many jsp (> 500) the plugin can take lot of time to compile all files. (see the benchmark after)
The other problem is this plugin will stop and fail at the first jsp who contains error. 
And even at the first error in the jsp! If a jsp contains 5 errors, we must run 5 times the plugin to discover all.
So if a big project contains multiples errors, we must run may times the plugin and so many times the full compilation of all jsp.

== First fix : performance

In order to compile a big project faster, I propose different things

=== Give all jsp to Jasper JSPC

In version 1.1.0 of the plugin, it takes all of the jsp and call execute JSPC for each of them.
This is the code : 

[source,java]
====
for (String fileName : jspFiles) {
	jspc.setJspFiles(fileName);
	getLog().info("Compiling " + fileName);
	jspc.execute();
}

====

Maybe it's an optimization with Tomcat 6.X, but I think with Tomcat 8.X it's slower than giving all JSP directly to JSPC.execute();